# run commands for analysis,

# here goes your shell script
executable    = submitAnalysisJob.sh
#requirements = (OpSysAndVer =?= "CentOS7")
# here you specify where to put .log, .out and .err files
output                = /afs/cern.ch/work/s/saaumill/public/std-condor/job.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/s/saaumill/public/std-condor/job.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/s/saaumill/public/std-condor/job.$(ClusterId).$(ClusterId).log

+AccountingGroup = "group_u_FCC.local_gen"
+JobFlavour    = "espresso"
arguments="0 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /afs/cern.ch/work/s/saaumill/public/Hxx-inputNN-largedata_from_batch/ /afs/cern.ch/work/s/saaumill/public/Hxx-inputNN-largedata_from_batch/Hbb_0.root"
queue
