# run commands for analysis,

# here goes your shell script
executable    = submitAnalysisJob.sh
#requirements = (OpSysAndVer =?= "CentOS7")
# here you specify where to put .log, .out and .err files
output                = /afs/cern.ch/work/s/saaumill/public/std-condor/job.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/s/saaumill/public/std-condor/job.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/s/saaumill/public/std-condor/job.$(ClusterId).$(ClusterId).log

+AccountingGroup = "group_u_FCC.local_gen"
+JobFlavour    = "microcentury"
arguments="0 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_0.root"
queue
arguments="50 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_1.root"
queue
arguments="100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_2.root"
queue
arguments="150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_3.root"
queue
arguments="200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_4.root"
queue
arguments="250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_5.root"
queue
arguments="300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_6.root"
queue
arguments="350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_7.root"
queue
arguments="400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_8.root"
queue
arguments="450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_9.root"
queue
arguments="500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_10.root"
queue
arguments="550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_11.root"
queue
arguments="600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_12.root"
queue
arguments="650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_13.root"
queue
arguments="700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_14.root"
queue
arguments="750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_15.root"
queue
arguments="800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_16.root"
queue
arguments="850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_17.root"
queue
arguments="900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_18.root"
queue
arguments="950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_19.root"
queue
arguments="1000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_20.root"
queue
arguments="1050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_21.root"
queue
arguments="1100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_22.root"
queue
arguments="1150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_23.root"
queue
arguments="1200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_24.root"
queue
arguments="1250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_25.root"
queue
arguments="1300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_26.root"
queue
arguments="1350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_27.root"
queue
arguments="1400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_28.root"
queue
arguments="1450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_29.root"
queue
arguments="1500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_30.root"
queue
arguments="1550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_31.root"
queue
arguments="1600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_32.root"
queue
arguments="1650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_33.root"
queue
arguments="1700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_34.root"
queue
arguments="1750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_35.root"
queue
arguments="1800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_36.root"
queue
arguments="1850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_37.root"
queue
arguments="1900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_38.root"
queue
arguments="1950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_39.root"
queue
arguments="2000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_40.root"
queue
arguments="2050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_41.root"
queue
arguments="2100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_42.root"
queue
arguments="2150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_43.root"
queue
arguments="2200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_44.root"
queue
arguments="2250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_45.root"
queue
arguments="2300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_46.root"
queue
arguments="2350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_47.root"
queue
arguments="2400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_48.root"
queue
arguments="2450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_49.root"
queue
arguments="2500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_50.root"
queue
arguments="2550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_51.root"
queue
arguments="2600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_52.root"
queue
arguments="2650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_53.root"
queue
arguments="2700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_54.root"
queue
arguments="2750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_55.root"
queue
arguments="2800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_56.root"
queue
arguments="2850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_57.root"
queue
arguments="2900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_58.root"
queue
arguments="2950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_59.root"
queue
arguments="3000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_60.root"
queue
arguments="3050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_61.root"
queue
arguments="3100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_62.root"
queue
arguments="3150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_63.root"
queue
arguments="3200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_64.root"
queue
arguments="3250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_65.root"
queue
arguments="3300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_66.root"
queue
arguments="3350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_67.root"
queue
arguments="3400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_68.root"
queue
arguments="3450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_69.root"
queue
arguments="3500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_70.root"
queue
arguments="3550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_71.root"
queue
arguments="3600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_72.root"
queue
arguments="3650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_73.root"
queue
arguments="3700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_74.root"
queue
arguments="3750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_75.root"
queue
arguments="3800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_76.root"
queue
arguments="3850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_77.root"
queue
arguments="3900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_78.root"
queue
arguments="3950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_79.root"
queue
arguments="4000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_80.root"
queue
arguments="4050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_81.root"
queue
arguments="4100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_82.root"
queue
arguments="4150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_83.root"
queue
arguments="4200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_84.root"
queue
arguments="4250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_85.root"
queue
arguments="4300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_86.root"
queue
arguments="4350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_87.root"
queue
arguments="4400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_88.root"
queue
arguments="4450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_89.root"
queue
arguments="4500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_90.root"
queue
arguments="4550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_91.root"
queue
arguments="4600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_92.root"
queue
arguments="4650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_93.root"
queue
arguments="4700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_94.root"
queue
arguments="4750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_95.root"
queue
arguments="4800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_96.root"
queue
arguments="4850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_97.root"
queue
arguments="4900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_98.root"
queue
arguments="4950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_99.root"
queue
arguments="5000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_100.root"
queue
arguments="5050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_101.root"
queue
arguments="5100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_102.root"
queue
arguments="5150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_103.root"
queue
arguments="5200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_104.root"
queue
arguments="5250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_105.root"
queue
arguments="5300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_106.root"
queue
arguments="5350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_107.root"
queue
arguments="5400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_108.root"
queue
arguments="5450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_109.root"
queue
arguments="5500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_110.root"
queue
arguments="5550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_111.root"
queue
arguments="5600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_112.root"
queue
arguments="5650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_113.root"
queue
arguments="5700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_114.root"
queue
arguments="5750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_115.root"
queue
arguments="5800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_116.root"
queue
arguments="5850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_117.root"
queue
arguments="5900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_118.root"
queue
arguments="5950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_119.root"
queue
arguments="6000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_120.root"
queue
arguments="6050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_121.root"
queue
arguments="6100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_122.root"
queue
arguments="6150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_123.root"
queue
arguments="6200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_124.root"
queue
arguments="6250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_125.root"
queue
arguments="6300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_126.root"
queue
arguments="6350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_127.root"
queue
arguments="6400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_128.root"
queue
arguments="6450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_129.root"
queue
arguments="6500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_130.root"
queue
arguments="6550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_131.root"
queue
arguments="6600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_132.root"
queue
arguments="6650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_133.root"
queue
arguments="6700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_134.root"
queue
arguments="6750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_135.root"
queue
arguments="6800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_136.root"
queue
arguments="6850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_137.root"
queue
arguments="6900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_138.root"
queue
arguments="6950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_139.root"
queue
arguments="7000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_140.root"
queue
arguments="7050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_141.root"
queue
arguments="7100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_142.root"
queue
arguments="7150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_143.root"
queue
arguments="7200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_144.root"
queue
arguments="7250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_145.root"
queue
arguments="7300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_146.root"
queue
arguments="7350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_147.root"
queue
arguments="7400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_148.root"
queue
arguments="7450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_149.root"
queue
arguments="7500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_150.root"
queue
arguments="7550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_151.root"
queue
arguments="7600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_152.root"
queue
arguments="7650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_153.root"
queue
arguments="7700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_154.root"
queue
arguments="7750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_155.root"
queue
arguments="7800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_156.root"
queue
arguments="7850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_157.root"
queue
arguments="7900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_158.root"
queue
arguments="7950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_159.root"
queue
arguments="8000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_160.root"
queue
arguments="8050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_161.root"
queue
arguments="8100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_162.root"
queue
arguments="8150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_163.root"
queue
arguments="8200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_164.root"
queue
arguments="8250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_165.root"
queue
arguments="8300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_166.root"
queue
arguments="8350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_167.root"
queue
arguments="8400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_168.root"
queue
arguments="8450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_169.root"
queue
arguments="8500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_170.root"
queue
arguments="8550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_171.root"
queue
arguments="8600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_172.root"
queue
arguments="8650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_173.root"
queue
arguments="8700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_174.root"
queue
arguments="8750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_175.root"
queue
arguments="8800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_176.root"
queue
arguments="8850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_177.root"
queue
arguments="8900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_178.root"
queue
arguments="8950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_179.root"
queue
arguments="9000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_180.root"
queue
arguments="9050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_181.root"
queue
arguments="9100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_182.root"
queue
arguments="9150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_183.root"
queue
arguments="9200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_184.root"
queue
arguments="9250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_185.root"
queue
arguments="9300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_186.root"
queue
arguments="9350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_187.root"
queue
arguments="9400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_188.root"
queue
arguments="9450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_189.root"
queue
arguments="9500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_190.root"
queue
arguments="9550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_191.root"
queue
arguments="9600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_192.root"
queue
arguments="9650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_193.root"
queue
arguments="9700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_194.root"
queue
arguments="9750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_195.root"
queue
arguments="9800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_196.root"
queue
arguments="9850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_197.root"
queue
arguments="9900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_198.root"
queue
arguments="9950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_199.root"
queue
arguments="0 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_200.root"
queue
arguments="50 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_201.root"
queue
arguments="100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_202.root"
queue
arguments="150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_203.root"
queue
arguments="200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_204.root"
queue
arguments="250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_205.root"
queue
arguments="300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_206.root"
queue
arguments="350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_207.root"
queue
arguments="400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_208.root"
queue
arguments="450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_209.root"
queue
arguments="500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_210.root"
queue
arguments="550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_211.root"
queue
arguments="600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_212.root"
queue
arguments="650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_213.root"
queue
arguments="700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_214.root"
queue
arguments="750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_215.root"
queue
arguments="800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_216.root"
queue
arguments="850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_217.root"
queue
arguments="900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_218.root"
queue
arguments="950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_219.root"
queue
arguments="1000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_220.root"
queue
arguments="1050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_221.root"
queue
arguments="1100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_222.root"
queue
arguments="1150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_223.root"
queue
arguments="1200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_224.root"
queue
arguments="1250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_225.root"
queue
arguments="1300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_226.root"
queue
arguments="1350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_227.root"
queue
arguments="1400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_228.root"
queue
arguments="1450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_229.root"
queue
arguments="1500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_230.root"
queue
arguments="1550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_231.root"
queue
arguments="1600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_232.root"
queue
arguments="1650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_233.root"
queue
arguments="1700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_234.root"
queue
arguments="1750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_235.root"
queue
arguments="1800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_236.root"
queue
arguments="1850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_237.root"
queue
arguments="1900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_238.root"
queue
arguments="1950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_239.root"
queue
arguments="2000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_240.root"
queue
arguments="2050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_241.root"
queue
arguments="2100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_242.root"
queue
arguments="2150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_243.root"
queue
arguments="2200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_244.root"
queue
arguments="2250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_245.root"
queue
arguments="2300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_246.root"
queue
arguments="2350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_247.root"
queue
arguments="2400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_248.root"
queue
arguments="2450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_249.root"
queue
arguments="2500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_250.root"
queue
arguments="2550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_251.root"
queue
arguments="2600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_252.root"
queue
arguments="2650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_253.root"
queue
arguments="2700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_254.root"
queue
arguments="2750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_255.root"
queue
arguments="2800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_256.root"
queue
arguments="2850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_257.root"
queue
arguments="2900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_258.root"
queue
arguments="2950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_259.root"
queue
arguments="3000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_260.root"
queue
arguments="3050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_261.root"
queue
arguments="3100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_262.root"
queue
arguments="3150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_263.root"
queue
arguments="3200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_264.root"
queue
arguments="3250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_265.root"
queue
arguments="3300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_266.root"
queue
arguments="3350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_267.root"
queue
arguments="3400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_268.root"
queue
arguments="3450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_269.root"
queue
arguments="3500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_270.root"
queue
arguments="3550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_271.root"
queue
arguments="3600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_272.root"
queue
arguments="3650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_273.root"
queue
arguments="3700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_274.root"
queue
arguments="3750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_275.root"
queue
arguments="3800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_276.root"
queue
arguments="3850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_277.root"
queue
arguments="3900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_278.root"
queue
arguments="3950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_279.root"
queue
arguments="4000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_280.root"
queue
arguments="4050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_281.root"
queue
arguments="4100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_282.root"
queue
arguments="4150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_283.root"
queue
arguments="4200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_284.root"
queue
arguments="4250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_285.root"
queue
arguments="4300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_286.root"
queue
arguments="4350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_287.root"
queue
arguments="4400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_288.root"
queue
arguments="4450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_289.root"
queue
arguments="4500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_290.root"
queue
arguments="4550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_291.root"
queue
arguments="4600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_292.root"
queue
arguments="4650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_293.root"
queue
arguments="4700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_294.root"
queue
arguments="4750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_295.root"
queue
arguments="4800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_296.root"
queue
arguments="4850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_297.root"
queue
arguments="4900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_298.root"
queue
arguments="4950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_299.root"
queue
arguments="5000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_300.root"
queue
arguments="5050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_301.root"
queue
arguments="5100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_302.root"
queue
arguments="5150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_303.root"
queue
arguments="5200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_304.root"
queue
arguments="5250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_305.root"
queue
arguments="5300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_306.root"
queue
arguments="5350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_307.root"
queue
arguments="5400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_308.root"
queue
arguments="5450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_309.root"
queue
arguments="5500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_310.root"
queue
arguments="5550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_311.root"
queue
arguments="5600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_312.root"
queue
arguments="5650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_313.root"
queue
arguments="5700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_314.root"
queue
arguments="5750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_315.root"
queue
arguments="5800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_316.root"
queue
arguments="5850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_317.root"
queue
arguments="5900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_318.root"
queue
arguments="5950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_319.root"
queue
arguments="6000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_320.root"
queue
arguments="6050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_321.root"
queue
arguments="6100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_322.root"
queue
arguments="6150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_323.root"
queue
arguments="6200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_324.root"
queue
arguments="6250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_325.root"
queue
arguments="6300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_326.root"
queue
arguments="6350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_327.root"
queue
arguments="6400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_328.root"
queue
arguments="6450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_329.root"
queue
arguments="6500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_330.root"
queue
arguments="6550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_331.root"
queue
arguments="6600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_332.root"
queue
arguments="6650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_333.root"
queue
arguments="6700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_334.root"
queue
arguments="6750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_335.root"
queue
arguments="6800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_336.root"
queue
arguments="6850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_337.root"
queue
arguments="6900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_338.root"
queue
arguments="6950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_339.root"
queue
arguments="7000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_340.root"
queue
arguments="7050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_341.root"
queue
arguments="7100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_342.root"
queue
arguments="7150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_343.root"
queue
arguments="7200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_344.root"
queue
arguments="7250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_345.root"
queue
arguments="7300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_346.root"
queue
arguments="7350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_347.root"
queue
arguments="7400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_348.root"
queue
arguments="7450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_349.root"
queue
arguments="7500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_350.root"
queue
arguments="7550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_351.root"
queue
arguments="7600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_352.root"
queue
arguments="7650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_353.root"
queue
arguments="7700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_354.root"
queue
arguments="7750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_355.root"
queue
arguments="7800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_356.root"
queue
arguments="7850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_357.root"
queue
arguments="7900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_358.root"
queue
arguments="7950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_359.root"
queue
arguments="8000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_360.root"
queue
arguments="8050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_361.root"
queue
arguments="8100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_362.root"
queue
arguments="8150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_363.root"
queue
arguments="8200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_364.root"
queue
arguments="8250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_365.root"
queue
arguments="8300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_366.root"
queue
arguments="8350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_367.root"
queue
arguments="8400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_368.root"
queue
arguments="8450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_369.root"
queue
arguments="8500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_370.root"
queue
arguments="8550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_371.root"
queue
arguments="8600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_372.root"
queue
arguments="8650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_373.root"
queue
arguments="8700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_374.root"
queue
arguments="8750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_375.root"
queue
arguments="8800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_376.root"
queue
arguments="8850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_377.root"
queue
arguments="8900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_378.root"
queue
arguments="8950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_379.root"
queue
arguments="9000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_380.root"
queue
arguments="9050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_381.root"
queue
arguments="9100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_382.root"
queue
arguments="9150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_383.root"
queue
arguments="9200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_384.root"
queue
arguments="9250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_385.root"
queue
arguments="9300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_386.root"
queue
arguments="9350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_387.root"
queue
arguments="9400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_388.root"
queue
arguments="9450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_389.root"
queue
arguments="9500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_390.root"
queue
arguments="9550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_391.root"
queue
arguments="9600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_392.root"
queue
arguments="9650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_393.root"
queue
arguments="9700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_394.root"
queue
arguments="9750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_395.root"
queue
arguments="9800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_396.root"
queue
arguments="9850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_397.root"
queue
arguments="9900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_398.root"
queue
arguments="9950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_399.root"
queue
arguments="0 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_400.root"
queue
arguments="50 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_401.root"
queue
arguments="100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_402.root"
queue
arguments="150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_403.root"
queue
arguments="200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_404.root"
queue
arguments="250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_405.root"
queue
arguments="300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_406.root"
queue
arguments="350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_407.root"
queue
arguments="400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_408.root"
queue
arguments="450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_409.root"
queue
arguments="500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_410.root"
queue
arguments="550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_411.root"
queue
arguments="600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_412.root"
queue
arguments="650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_413.root"
queue
arguments="700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_414.root"
queue
arguments="750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_415.root"
queue
arguments="800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_416.root"
queue
arguments="850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_417.root"
queue
arguments="900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_418.root"
queue
arguments="950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_419.root"
queue
arguments="1000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_420.root"
queue
arguments="1050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_421.root"
queue
arguments="1100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_422.root"
queue
arguments="1150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_423.root"
queue
arguments="1200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_424.root"
queue
arguments="1250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_425.root"
queue
arguments="1300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_426.root"
queue
arguments="1350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_427.root"
queue
arguments="1400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_428.root"
queue
arguments="1450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_429.root"
queue
arguments="1500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_430.root"
queue
arguments="1550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_431.root"
queue
arguments="1600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_432.root"
queue
arguments="1650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_433.root"
queue
arguments="1700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_434.root"
queue
arguments="1750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_435.root"
queue
arguments="1800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_436.root"
queue
arguments="1850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_437.root"
queue
arguments="1900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_438.root"
queue
arguments="1950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_439.root"
queue
arguments="2000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_440.root"
queue
arguments="2050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_441.root"
queue
arguments="2100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_442.root"
queue
arguments="2150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_443.root"
queue
arguments="2200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_444.root"
queue
arguments="2250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_445.root"
queue
arguments="2300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_446.root"
queue
arguments="2350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_447.root"
queue
arguments="2400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_448.root"
queue
arguments="2450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_449.root"
queue
arguments="2500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_450.root"
queue
arguments="2550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_451.root"
queue
arguments="2600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_452.root"
queue
arguments="2650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_453.root"
queue
arguments="2700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_454.root"
queue
arguments="2750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_455.root"
queue
arguments="2800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_456.root"
queue
arguments="2850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_457.root"
queue
arguments="2900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_458.root"
queue
arguments="2950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_459.root"
queue
arguments="3000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_460.root"
queue
arguments="3050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_461.root"
queue
arguments="3100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_462.root"
queue
arguments="3150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_463.root"
queue
arguments="3200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_464.root"
queue
arguments="3250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_465.root"
queue
arguments="3300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_466.root"
queue
arguments="3350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_467.root"
queue
arguments="3400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_468.root"
queue
arguments="3450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_469.root"
queue
arguments="3500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_470.root"
queue
arguments="3550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_471.root"
queue
arguments="3600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_472.root"
queue
arguments="3650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_473.root"
queue
arguments="3700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_474.root"
queue
arguments="3750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_475.root"
queue
arguments="3800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_476.root"
queue
arguments="3850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_477.root"
queue
arguments="3900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_478.root"
queue
arguments="3950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_479.root"
queue
arguments="4000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_480.root"
queue
arguments="4050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_481.root"
queue
arguments="4100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_482.root"
queue
arguments="4150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_483.root"
queue
arguments="4200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_484.root"
queue
arguments="4250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_485.root"
queue
arguments="4300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_486.root"
queue
arguments="4350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_487.root"
queue
arguments="4400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_488.root"
queue
arguments="4450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_489.root"
queue
arguments="4500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_490.root"
queue
arguments="4550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_491.root"
queue
arguments="4600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_492.root"
queue
arguments="4650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_493.root"
queue
arguments="4700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_494.root"
queue
arguments="4750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_495.root"
queue
arguments="4800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_496.root"
queue
arguments="4850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_497.root"
queue
arguments="4900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_498.root"
queue
arguments="4950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_499.root"
queue
arguments="5000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_500.root"
queue
arguments="5050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_501.root"
queue
arguments="5100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_502.root"
queue
arguments="5150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_503.root"
queue
arguments="5200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_504.root"
queue
arguments="5250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_505.root"
queue
arguments="5300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_506.root"
queue
arguments="5350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_507.root"
queue
arguments="5400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_508.root"
queue
arguments="5450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_509.root"
queue
arguments="5500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_510.root"
queue
arguments="5550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_511.root"
queue
arguments="5600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_512.root"
queue
arguments="5650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_513.root"
queue
arguments="5700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_514.root"
queue
arguments="5750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_515.root"
queue
arguments="5800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_516.root"
queue
arguments="5850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_517.root"
queue
arguments="5900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_518.root"
queue
arguments="5950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_519.root"
queue
arguments="6000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_520.root"
queue
arguments="6050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_521.root"
queue
arguments="6100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_522.root"
queue
arguments="6150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_523.root"
queue
arguments="6200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_524.root"
queue
arguments="6250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_525.root"
queue
arguments="6300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_526.root"
queue
arguments="6350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_527.root"
queue
arguments="6400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_528.root"
queue
arguments="6450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_529.root"
queue
arguments="6500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_530.root"
queue
arguments="6550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_531.root"
queue
arguments="6600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_532.root"
queue
arguments="6650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_533.root"
queue
arguments="6700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_534.root"
queue
arguments="6750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_535.root"
queue
arguments="6800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_536.root"
queue
arguments="6850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_537.root"
queue
arguments="6900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_538.root"
queue
arguments="6950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_539.root"
queue
arguments="7000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_540.root"
queue
arguments="7050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_541.root"
queue
arguments="7100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_542.root"
queue
arguments="7150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_543.root"
queue
arguments="7200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_544.root"
queue
arguments="7250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_545.root"
queue
arguments="7300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_546.root"
queue
arguments="7350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_547.root"
queue
arguments="7400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_548.root"
queue
arguments="7450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_549.root"
queue
arguments="7500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_550.root"
queue
arguments="7550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_551.root"
queue
arguments="7600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_552.root"
queue
arguments="7650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_553.root"
queue
arguments="7700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_554.root"
queue
arguments="7750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_555.root"
queue
arguments="7800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_556.root"
queue
arguments="7850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_557.root"
queue
arguments="7900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_558.root"
queue
arguments="7950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_559.root"
queue
arguments="8000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_560.root"
queue
arguments="8050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_561.root"
queue
arguments="8100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_562.root"
queue
arguments="8150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_563.root"
queue
arguments="8200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_564.root"
queue
arguments="8250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_565.root"
queue
arguments="8300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_566.root"
queue
arguments="8350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_567.root"
queue
arguments="8400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_568.root"
queue
arguments="8450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_569.root"
queue
arguments="8500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_570.root"
queue
arguments="8550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_571.root"
queue
arguments="8600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_572.root"
queue
arguments="8650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_573.root"
queue
arguments="8700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_574.root"
queue
arguments="8750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_575.root"
queue
arguments="8800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_576.root"
queue
arguments="8850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_577.root"
queue
arguments="8900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_578.root"
queue
arguments="8950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_579.root"
queue
arguments="9000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_580.root"
queue
arguments="9050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_581.root"
queue
arguments="9100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_582.root"
queue
arguments="9150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_583.root"
queue
arguments="9200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_584.root"
queue
arguments="9250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_585.root"
queue
arguments="9300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_586.root"
queue
arguments="9350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_587.root"
queue
arguments="9400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_588.root"
queue
arguments="9450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_589.root"
queue
arguments="9500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_590.root"
queue
arguments="9550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_591.root"
queue
arguments="9600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_592.root"
queue
arguments="9650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_593.root"
queue
arguments="9700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_594.root"
queue
arguments="9750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_595.root"
queue
arguments="9800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_596.root"
queue
arguments="9850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_597.root"
queue
arguments="9900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_598.root"
queue
arguments="9950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_599.root"
queue
