# run commands for analysis,

# here goes your shell script
executable    = submitAnalysisJob.sh
#requirements = (OpSysAndVer =?= "CentOS7")
# here you specify where to put .log, .out and .err files
output                = /afs/cern.ch/work/s/saaumill/public/std-condor/job.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/s/saaumill/public/std-condor/job.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/s/saaumill/public/std-condor/job.$(ClusterId).$(ClusterId).log

+AccountingGroup = "group_u_FCC.local_gen"
+JobFlavour    = "microcentury"
arguments="0 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_0.root"
queue
arguments="50 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_1.root"
queue
arguments="100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_2.root"
queue
arguments="150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_3.root"
queue
arguments="200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_4.root"
queue
arguments="250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_5.root"
queue
arguments="300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_6.root"
queue
arguments="350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_7.root"
queue
arguments="400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_8.root"
queue
arguments="450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_9.root"
queue
arguments="500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_10.root"
queue
arguments="550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_11.root"
queue
arguments="600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_12.root"
queue
arguments="650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_13.root"
queue
arguments="700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_14.root"
queue
arguments="750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_15.root"
queue
arguments="800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_16.root"
queue
arguments="850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_17.root"
queue
arguments="900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_18.root"
queue
arguments="950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_19.root"
queue
arguments="1000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_20.root"
queue
arguments="1050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_21.root"
queue
arguments="1100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_22.root"
queue
arguments="1150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_23.root"
queue
arguments="1200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_24.root"
queue
arguments="1250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_25.root"
queue
arguments="1300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_26.root"
queue
arguments="1350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_27.root"
queue
arguments="1400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_28.root"
queue
arguments="1450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_29.root"
queue
arguments="1500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_30.root"
queue
arguments="1550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_31.root"
queue
arguments="1600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_32.root"
queue
arguments="1650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_33.root"
queue
arguments="1700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_34.root"
queue
arguments="1750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_35.root"
queue
arguments="1800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_36.root"
queue
arguments="1850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_37.root"
queue
arguments="1900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_38.root"
queue
arguments="1950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_39.root"
queue
arguments="2000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_40.root"
queue
arguments="2050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_41.root"
queue
arguments="2100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_42.root"
queue
arguments="2150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_43.root"
queue
arguments="2200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_44.root"
queue
arguments="2250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_45.root"
queue
arguments="2300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_46.root"
queue
arguments="2350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_47.root"
queue
arguments="2400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_48.root"
queue
arguments="2450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_49.root"
queue
arguments="2500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_50.root"
queue
arguments="2550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_51.root"
queue
arguments="2600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_52.root"
queue
arguments="2650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_53.root"
queue
arguments="2700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_54.root"
queue
arguments="2750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_55.root"
queue
arguments="2800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_56.root"
queue
arguments="2850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_57.root"
queue
arguments="2900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_58.root"
queue
arguments="2950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_59.root"
queue
arguments="3000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_60.root"
queue
arguments="3050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_61.root"
queue
arguments="3100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_62.root"
queue
arguments="3150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_63.root"
queue
arguments="3200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_64.root"
queue
arguments="3250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_65.root"
queue
arguments="3300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_66.root"
queue
arguments="3350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_67.root"
queue
arguments="3400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_68.root"
queue
arguments="3450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_69.root"
queue
arguments="3500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_70.root"
queue
arguments="3550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_71.root"
queue
arguments="3600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_72.root"
queue
arguments="3650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_73.root"
queue
arguments="3700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_74.root"
queue
arguments="3750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_75.root"
queue
arguments="3800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_76.root"
queue
arguments="3850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_77.root"
queue
arguments="3900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_78.root"
queue
arguments="3950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_79.root"
queue
arguments="4000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_80.root"
queue
arguments="4050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_81.root"
queue
arguments="4100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_82.root"
queue
arguments="4150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_83.root"
queue
arguments="4200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_84.root"
queue
arguments="4250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_85.root"
queue
arguments="4300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_86.root"
queue
arguments="4350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_87.root"
queue
arguments="4400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_88.root"
queue
arguments="4450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_89.root"
queue
arguments="4500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_90.root"
queue
arguments="4550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_91.root"
queue
arguments="4600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_92.root"
queue
arguments="4650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_93.root"
queue
arguments="4700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_94.root"
queue
arguments="4750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_95.root"
queue
arguments="4800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_96.root"
queue
arguments="4850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_97.root"
queue
arguments="4900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_98.root"
queue
arguments="4950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_99.root"
queue
arguments="5000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_100.root"
queue
arguments="5050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_101.root"
queue
arguments="5100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_102.root"
queue
arguments="5150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_103.root"
queue
arguments="5200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_104.root"
queue
arguments="5250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_105.root"
queue
arguments="5300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_106.root"
queue
arguments="5350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_107.root"
queue
arguments="5400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_108.root"
queue
arguments="5450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_109.root"
queue
arguments="5500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_110.root"
queue
arguments="5550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_111.root"
queue
arguments="5600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_112.root"
queue
arguments="5650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_113.root"
queue
arguments="5700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_114.root"
queue
arguments="5750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_115.root"
queue
arguments="5800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_116.root"
queue
arguments="5850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_117.root"
queue
arguments="5900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_118.root"
queue
arguments="5950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_119.root"
queue
arguments="6000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_120.root"
queue
arguments="6050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_121.root"
queue
arguments="6100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_122.root"
queue
arguments="6150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_123.root"
queue
arguments="6200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_124.root"
queue
arguments="6250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_125.root"
queue
arguments="6300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_126.root"
queue
arguments="6350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_127.root"
queue
arguments="6400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_128.root"
queue
arguments="6450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_129.root"
queue
arguments="6500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_130.root"
queue
arguments="6550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_131.root"
queue
arguments="6600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_132.root"
queue
arguments="6650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_133.root"
queue
arguments="6700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_134.root"
queue
arguments="6750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_135.root"
queue
arguments="6800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_136.root"
queue
arguments="6850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_137.root"
queue
arguments="6900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_138.root"
queue
arguments="6950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_139.root"
queue
arguments="7000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_140.root"
queue
arguments="7050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_141.root"
queue
arguments="7100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_142.root"
queue
arguments="7150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_143.root"
queue
arguments="7200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_144.root"
queue
arguments="7250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_145.root"
queue
arguments="7300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_146.root"
queue
arguments="7350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_147.root"
queue
arguments="7400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_148.root"
queue
arguments="7450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_149.root"
queue
arguments="7500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_150.root"
queue
arguments="7550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_151.root"
queue
arguments="7600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_152.root"
queue
arguments="7650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_153.root"
queue
arguments="7700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_154.root"
queue
arguments="7750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_155.root"
queue
arguments="7800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_156.root"
queue
arguments="7850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_157.root"
queue
arguments="7900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_158.root"
queue
arguments="7950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_159.root"
queue
arguments="8000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_160.root"
queue
arguments="8050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_161.root"
queue
arguments="8100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_162.root"
queue
arguments="8150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_163.root"
queue
arguments="8200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_164.root"
queue
arguments="8250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_165.root"
queue
arguments="8300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_166.root"
queue
arguments="8350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_167.root"
queue
arguments="8400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_168.root"
queue
arguments="8450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_169.root"
queue
arguments="8500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_170.root"
queue
arguments="8550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_171.root"
queue
arguments="8600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_172.root"
queue
arguments="8650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_173.root"
queue
arguments="8700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_174.root"
queue
arguments="8750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_175.root"
queue
arguments="8800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_176.root"
queue
arguments="8850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_177.root"
queue
arguments="8900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_178.root"
queue
arguments="8950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_179.root"
queue
arguments="9000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_180.root"
queue
arguments="9050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_181.root"
queue
arguments="9100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_182.root"
queue
arguments="9150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_183.root"
queue
arguments="9200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_184.root"
queue
arguments="9250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_185.root"
queue
arguments="9300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_186.root"
queue
arguments="9350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_187.root"
queue
arguments="9400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_188.root"
queue
arguments="9450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_189.root"
queue
arguments="9500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_190.root"
queue
arguments="9550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_191.root"
queue
arguments="9600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_192.root"
queue
arguments="9650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_193.root"
queue
arguments="9700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_194.root"
queue
arguments="9750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_195.root"
queue
arguments="9800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_196.root"
queue
arguments="9850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_197.root"
queue
arguments="9900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_198.root"
queue
arguments="9950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hbb/CLD_o2_v05/rec/*/*/Hbb_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hbb_199.root"
queue
arguments="0 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_0.root"
queue
arguments="50 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_1.root"
queue
arguments="100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_2.root"
queue
arguments="150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_3.root"
queue
arguments="200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_4.root"
queue
arguments="250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_5.root"
queue
arguments="300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_6.root"
queue
arguments="350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_7.root"
queue
arguments="400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_8.root"
queue
arguments="450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_9.root"
queue
arguments="500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_10.root"
queue
arguments="550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_11.root"
queue
arguments="600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_12.root"
queue
arguments="650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_13.root"
queue
arguments="700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_14.root"
queue
arguments="750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_15.root"
queue
arguments="800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_16.root"
queue
arguments="850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_17.root"
queue
arguments="900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_18.root"
queue
arguments="950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_19.root"
queue
arguments="1000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_20.root"
queue
arguments="1050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_21.root"
queue
arguments="1100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_22.root"
queue
arguments="1150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_23.root"
queue
arguments="1200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_24.root"
queue
arguments="1250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_25.root"
queue
arguments="1300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_26.root"
queue
arguments="1350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_27.root"
queue
arguments="1400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_28.root"
queue
arguments="1450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_29.root"
queue
arguments="1500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_30.root"
queue
arguments="1550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_31.root"
queue
arguments="1600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_32.root"
queue
arguments="1650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_33.root"
queue
arguments="1700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_34.root"
queue
arguments="1750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_35.root"
queue
arguments="1800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_36.root"
queue
arguments="1850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_37.root"
queue
arguments="1900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_38.root"
queue
arguments="1950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_39.root"
queue
arguments="2000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_40.root"
queue
arguments="2050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_41.root"
queue
arguments="2100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_42.root"
queue
arguments="2150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_43.root"
queue
arguments="2200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_44.root"
queue
arguments="2250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_45.root"
queue
arguments="2300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_46.root"
queue
arguments="2350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_47.root"
queue
arguments="2400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_48.root"
queue
arguments="2450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_49.root"
queue
arguments="2500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_50.root"
queue
arguments="2550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_51.root"
queue
arguments="2600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_52.root"
queue
arguments="2650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_53.root"
queue
arguments="2700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_54.root"
queue
arguments="2750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_55.root"
queue
arguments="2800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_56.root"
queue
arguments="2850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_57.root"
queue
arguments="2900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_58.root"
queue
arguments="2950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_59.root"
queue
arguments="3000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_60.root"
queue
arguments="3050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_61.root"
queue
arguments="3100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_62.root"
queue
arguments="3150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_63.root"
queue
arguments="3200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_64.root"
queue
arguments="3250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_65.root"
queue
arguments="3300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_66.root"
queue
arguments="3350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_67.root"
queue
arguments="3400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_68.root"
queue
arguments="3450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_69.root"
queue
arguments="3500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_70.root"
queue
arguments="3550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_71.root"
queue
arguments="3600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_72.root"
queue
arguments="3650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_73.root"
queue
arguments="3700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_74.root"
queue
arguments="3750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_75.root"
queue
arguments="3800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_76.root"
queue
arguments="3850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_77.root"
queue
arguments="3900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_78.root"
queue
arguments="3950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_79.root"
queue
arguments="4000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_80.root"
queue
arguments="4050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_81.root"
queue
arguments="4100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_82.root"
queue
arguments="4150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_83.root"
queue
arguments="4200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_84.root"
queue
arguments="4250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_85.root"
queue
arguments="4300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_86.root"
queue
arguments="4350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_87.root"
queue
arguments="4400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_88.root"
queue
arguments="4450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_89.root"
queue
arguments="4500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_90.root"
queue
arguments="4550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_91.root"
queue
arguments="4600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_92.root"
queue
arguments="4650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_93.root"
queue
arguments="4700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_94.root"
queue
arguments="4750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_95.root"
queue
arguments="4800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_96.root"
queue
arguments="4850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_97.root"
queue
arguments="4900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_98.root"
queue
arguments="4950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_99.root"
queue
arguments="5000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_100.root"
queue
arguments="5050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_101.root"
queue
arguments="5100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_102.root"
queue
arguments="5150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_103.root"
queue
arguments="5200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_104.root"
queue
arguments="5250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_105.root"
queue
arguments="5300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_106.root"
queue
arguments="5350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_107.root"
queue
arguments="5400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_108.root"
queue
arguments="5450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_109.root"
queue
arguments="5500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_110.root"
queue
arguments="5550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_111.root"
queue
arguments="5600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_112.root"
queue
arguments="5650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_113.root"
queue
arguments="5700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_114.root"
queue
arguments="5750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_115.root"
queue
arguments="5800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_116.root"
queue
arguments="5850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_117.root"
queue
arguments="5900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_118.root"
queue
arguments="5950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_119.root"
queue
arguments="6000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_120.root"
queue
arguments="6050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_121.root"
queue
arguments="6100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_122.root"
queue
arguments="6150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_123.root"
queue
arguments="6200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_124.root"
queue
arguments="6250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_125.root"
queue
arguments="6300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_126.root"
queue
arguments="6350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_127.root"
queue
arguments="6400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_128.root"
queue
arguments="6450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_129.root"
queue
arguments="6500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_130.root"
queue
arguments="6550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_131.root"
queue
arguments="6600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_132.root"
queue
arguments="6650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_133.root"
queue
arguments="6700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_134.root"
queue
arguments="6750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_135.root"
queue
arguments="6800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_136.root"
queue
arguments="6850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_137.root"
queue
arguments="6900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_138.root"
queue
arguments="6950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_139.root"
queue
arguments="7000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_140.root"
queue
arguments="7050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_141.root"
queue
arguments="7100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_142.root"
queue
arguments="7150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_143.root"
queue
arguments="7200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_144.root"
queue
arguments="7250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_145.root"
queue
arguments="7300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_146.root"
queue
arguments="7350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_147.root"
queue
arguments="7400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_148.root"
queue
arguments="7450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_149.root"
queue
arguments="7500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_150.root"
queue
arguments="7550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_151.root"
queue
arguments="7600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_152.root"
queue
arguments="7650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_153.root"
queue
arguments="7700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_154.root"
queue
arguments="7750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_155.root"
queue
arguments="7800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_156.root"
queue
arguments="7850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_157.root"
queue
arguments="7900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_158.root"
queue
arguments="7950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_159.root"
queue
arguments="8000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_160.root"
queue
arguments="8050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_161.root"
queue
arguments="8100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_162.root"
queue
arguments="8150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_163.root"
queue
arguments="8200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_164.root"
queue
arguments="8250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_165.root"
queue
arguments="8300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_166.root"
queue
arguments="8350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_167.root"
queue
arguments="8400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_168.root"
queue
arguments="8450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_169.root"
queue
arguments="8500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_170.root"
queue
arguments="8550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_171.root"
queue
arguments="8600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_172.root"
queue
arguments="8650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_173.root"
queue
arguments="8700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_174.root"
queue
arguments="8750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_175.root"
queue
arguments="8800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_176.root"
queue
arguments="8850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_177.root"
queue
arguments="8900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_178.root"
queue
arguments="8950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_179.root"
queue
arguments="9000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_180.root"
queue
arguments="9050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_181.root"
queue
arguments="9100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_182.root"
queue
arguments="9150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_183.root"
queue
arguments="9200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_184.root"
queue
arguments="9250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_185.root"
queue
arguments="9300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_186.root"
queue
arguments="9350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_187.root"
queue
arguments="9400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_188.root"
queue
arguments="9450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_189.root"
queue
arguments="9500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_190.root"
queue
arguments="9550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_191.root"
queue
arguments="9600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_192.root"
queue
arguments="9650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_193.root"
queue
arguments="9700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_194.root"
queue
arguments="9750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_195.root"
queue
arguments="9800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_196.root"
queue
arguments="9850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_197.root"
queue
arguments="9900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_198.root"
queue
arguments="9950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Hgg/CLD_o2_v05/rec/*/*/Hgg_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Hgg_199.root"
queue
arguments="0 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_0.root"
queue
arguments="50 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_1.root"
queue
arguments="100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_2.root"
queue
arguments="150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_3.root"
queue
arguments="200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_4.root"
queue
arguments="250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_5.root"
queue
arguments="300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_6.root"
queue
arguments="350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_7.root"
queue
arguments="400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_8.root"
queue
arguments="450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_9.root"
queue
arguments="500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_10.root"
queue
arguments="550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_11.root"
queue
arguments="600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_12.root"
queue
arguments="650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_13.root"
queue
arguments="700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_14.root"
queue
arguments="750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_15.root"
queue
arguments="800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_16.root"
queue
arguments="850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_17.root"
queue
arguments="900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_18.root"
queue
arguments="950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_19.root"
queue
arguments="1000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_20.root"
queue
arguments="1050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_21.root"
queue
arguments="1100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_22.root"
queue
arguments="1150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_23.root"
queue
arguments="1200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_24.root"
queue
arguments="1250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_25.root"
queue
arguments="1300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_26.root"
queue
arguments="1350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_27.root"
queue
arguments="1400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_28.root"
queue
arguments="1450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_29.root"
queue
arguments="1500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_30.root"
queue
arguments="1550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_31.root"
queue
arguments="1600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_32.root"
queue
arguments="1650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_33.root"
queue
arguments="1700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_34.root"
queue
arguments="1750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_35.root"
queue
arguments="1800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_36.root"
queue
arguments="1850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_37.root"
queue
arguments="1900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_38.root"
queue
arguments="1950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_39.root"
queue
arguments="2000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_40.root"
queue
arguments="2050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_41.root"
queue
arguments="2100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_42.root"
queue
arguments="2150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_43.root"
queue
arguments="2200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_44.root"
queue
arguments="2250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_45.root"
queue
arguments="2300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_46.root"
queue
arguments="2350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_47.root"
queue
arguments="2400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_48.root"
queue
arguments="2450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_49.root"
queue
arguments="2500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_50.root"
queue
arguments="2550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_51.root"
queue
arguments="2600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_52.root"
queue
arguments="2650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_53.root"
queue
arguments="2700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_54.root"
queue
arguments="2750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_55.root"
queue
arguments="2800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_56.root"
queue
arguments="2850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_57.root"
queue
arguments="2900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_58.root"
queue
arguments="2950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_59.root"
queue
arguments="3000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_60.root"
queue
arguments="3050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_61.root"
queue
arguments="3100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_62.root"
queue
arguments="3150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_63.root"
queue
arguments="3200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_64.root"
queue
arguments="3250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_65.root"
queue
arguments="3300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_66.root"
queue
arguments="3350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_67.root"
queue
arguments="3400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_68.root"
queue
arguments="3450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_69.root"
queue
arguments="3500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_70.root"
queue
arguments="3550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_71.root"
queue
arguments="3600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_72.root"
queue
arguments="3650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_73.root"
queue
arguments="3700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_74.root"
queue
arguments="3750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_75.root"
queue
arguments="3800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_76.root"
queue
arguments="3850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_77.root"
queue
arguments="3900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_78.root"
queue
arguments="3950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_79.root"
queue
arguments="4000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_80.root"
queue
arguments="4050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_81.root"
queue
arguments="4100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_82.root"
queue
arguments="4150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_83.root"
queue
arguments="4200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_84.root"
queue
arguments="4250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_85.root"
queue
arguments="4300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_86.root"
queue
arguments="4350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_87.root"
queue
arguments="4400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_88.root"
queue
arguments="4450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_89.root"
queue
arguments="4500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_90.root"
queue
arguments="4550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_91.root"
queue
arguments="4600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_92.root"
queue
arguments="4650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_93.root"
queue
arguments="4700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_94.root"
queue
arguments="4750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_95.root"
queue
arguments="4800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_96.root"
queue
arguments="4850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_97.root"
queue
arguments="4900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_98.root"
queue
arguments="4950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_99.root"
queue
arguments="5000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_100.root"
queue
arguments="5050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_101.root"
queue
arguments="5100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_102.root"
queue
arguments="5150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_103.root"
queue
arguments="5200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_104.root"
queue
arguments="5250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_105.root"
queue
arguments="5300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_106.root"
queue
arguments="5350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_107.root"
queue
arguments="5400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_108.root"
queue
arguments="5450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_109.root"
queue
arguments="5500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_110.root"
queue
arguments="5550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_111.root"
queue
arguments="5600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_112.root"
queue
arguments="5650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_113.root"
queue
arguments="5700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_114.root"
queue
arguments="5750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_115.root"
queue
arguments="5800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_116.root"
queue
arguments="5850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_117.root"
queue
arguments="5900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_118.root"
queue
arguments="5950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_119.root"
queue
arguments="6000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_120.root"
queue
arguments="6050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_121.root"
queue
arguments="6100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_122.root"
queue
arguments="6150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_123.root"
queue
arguments="6200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_124.root"
queue
arguments="6250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_125.root"
queue
arguments="6300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_126.root"
queue
arguments="6350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_127.root"
queue
arguments="6400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_128.root"
queue
arguments="6450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_129.root"
queue
arguments="6500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_130.root"
queue
arguments="6550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_131.root"
queue
arguments="6600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_132.root"
queue
arguments="6650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_133.root"
queue
arguments="6700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_134.root"
queue
arguments="6750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_135.root"
queue
arguments="6800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_136.root"
queue
arguments="6850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_137.root"
queue
arguments="6900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_138.root"
queue
arguments="6950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_139.root"
queue
arguments="7000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_140.root"
queue
arguments="7050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_141.root"
queue
arguments="7100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_142.root"
queue
arguments="7150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_143.root"
queue
arguments="7200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_144.root"
queue
arguments="7250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_145.root"
queue
arguments="7300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_146.root"
queue
arguments="7350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_147.root"
queue
arguments="7400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_148.root"
queue
arguments="7450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_149.root"
queue
arguments="7500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_150.root"
queue
arguments="7550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_151.root"
queue
arguments="7600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_152.root"
queue
arguments="7650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_153.root"
queue
arguments="7700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_154.root"
queue
arguments="7750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_155.root"
queue
arguments="7800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_156.root"
queue
arguments="7850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_157.root"
queue
arguments="7900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_158.root"
queue
arguments="7950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_159.root"
queue
arguments="8000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_160.root"
queue
arguments="8050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_161.root"
queue
arguments="8100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_162.root"
queue
arguments="8150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_163.root"
queue
arguments="8200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_164.root"
queue
arguments="8250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_165.root"
queue
arguments="8300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_166.root"
queue
arguments="8350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_167.root"
queue
arguments="8400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_168.root"
queue
arguments="8450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_169.root"
queue
arguments="8500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_170.root"
queue
arguments="8550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_171.root"
queue
arguments="8600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_172.root"
queue
arguments="8650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_173.root"
queue
arguments="8700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_174.root"
queue
arguments="8750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_175.root"
queue
arguments="8800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_176.root"
queue
arguments="8850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_177.root"
queue
arguments="8900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_178.root"
queue
arguments="8950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_179.root"
queue
arguments="9000 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_180.root"
queue
arguments="9050 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_181.root"
queue
arguments="9100 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_182.root"
queue
arguments="9150 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_183.root"
queue
arguments="9200 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_184.root"
queue
arguments="9250 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_185.root"
queue
arguments="9300 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_186.root"
queue
arguments="9350 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_187.root"
queue
arguments="9400 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_188.root"
queue
arguments="9450 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_189.root"
queue
arguments="9500 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_190.root"
queue
arguments="9550 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_191.root"
queue
arguments="9600 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_192.root"
queue
arguments="9650 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_193.root"
queue
arguments="9700 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_194.root"
queue
arguments="9750 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_195.root"
queue
arguments="9800 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_196.root"
queue
arguments="9850 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_197.root"
queue
arguments="9900 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_198.root"
queue
arguments="9950 50 '/eos/experiment/fcc/prod/fcc/ee/test_spring2024/240gev/Htautau/CLD_o2_v05/rec/*/*/Htautau_rec_*.root' /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/ /eos/experiment/fcc/ee/datasets/CLD_fullsim_tagging_trackPFOcheck/Htautau_199.root"
queue
